- id: '1537110407965'
  alias: Notify Doorbell
  trigger:
  - platform: webhook
    webhook_id: doorbell
  condition: []
  action:
  - data:
      entity_id: camera.porch_camera
      filename: /config/tmp/doorbell.jpg
    service: camera.snapshot
  - data:
      data:
        file:
          path: /config/tmp/doorbell.jpg
      message: Knock-knock!
      title: doorbell
    service: notify.slack
  mode: single
- id: '1538920016332'
  alias: Turn on PC at morning
  trigger:
  - at: '9:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.kirill_s_pc
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: switch.kirill_s_pc
    service: switch.turn_on
- id: '1540143489531'
  alias: Show message on Bedroom TV
  trigger:
  - entity_id: input_text.bedroom_tv_message
    platform: state
  condition: []
  action:
  - service: rest_command.bedroom_tv_message
- id: '1540533333691'
  alias: Notify New Device
  trigger:
  - event_data: {}
    event_type: device_tracker_new_device
    platform: event
  condition: []
  action:
  - data_template:
      message: New entity ID {{ trigger.event.data.entity_id }} and hostname {{ trigger.event.data.host_name
        }}
    service: notify.slack
  - data:
      message: New device
      target: 2171052962983820
    service: notify.facebook
- id: '1543758079076'
  alias: Notify Intercom
  trigger:
  - platform: webhook
    webhook_id: intercom
  condition: []
  action:
  - data:
      entity_id: camera.intercom_camera
      filename: /config/tmp/intercom.jpg
    service: camera.snapshot
  - data:
      data:
        file:
          path: /config/tmp/intercom.jpg
      message: Knock-knock!
      title: intercom
    service: notify.slack
  mode: single
- id: '1596309630141'
  alias: Backup Upload
  description: ''
  trigger:
  - at: '5:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: rest_command.google_backup
  mode: single
- id: '1596310309565'
  alias: Backup Create
  description: ''
  trigger:
  - at: '4:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: hassio.snapshot_full
  mode: single
- id: '1596440114103'
  alias: Startup States
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data: {}
    entity_id: switch.kitchen_second_light
    service: switch.turn_on
  mode: single
- id: '1596462187499'
  alias: DVR Slack
  description: ''
  trigger:
  - minutes: /5
    platform: time_pattern
  condition: []
  action:
  - data: {}
    service: shell_command.dvr_slack
  mode: single
- id: '1605209261256'
  alias: Hallway Light
  description: ''
  trigger:
  - platform: event
    event_data:
      name: SwitchHallwayOne
    event_type: sonoff.remote
  - platform: event
    event_type: sonoff.remote
    event_data:
      name: SwitchHallwayTwo
  condition: []
  action:
  - service: switch.toggle
    data: {}
    entity_id: switch.hallway_light
  mode: single
