- id: '1537110407965'
  alias: Slack Notify
  trigger:
  - entity_id: device_tracker.android2e62f0295f67a50e
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: camera.porch_camera
      filename: /tmp/doorbell.jpg
    service: camera.snapshot
  - data:
      data:
        file:
          path: /tmp/doorbell.jpg
      message: Lena's phone go away.
      title: Title of the file.
    service: notify.slack
- id: '1538920016332'
  alias: Turn on PC at morning
  trigger:
  - at: '9:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.kirills_pc
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: switch.kirills_pc
    service: switch.turn_on
