- id: '1537110407965'
  alias: Slack Doorbell Notify
  trigger:
  - platform: webhook
    webhook_id: doorbell
  condition: []
  action:
  - data:
      entity_id: camera.porch_camera
      filename: /tmp/doorbell.jpg
    service: camera.snapshot
  - data:
      data:
        file:
          path: /tmp/doorbell.jpg
      message: Knock-knock!
      title: doorbell
    service: notify.slack
- id: '1538920016332'
  alias: Turn on PC at morning
  trigger:
  - at: '9:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.kirills_pc
    state: 'off'
  action:
  - alias: ''
    data:
      entity_id: switch.kirills_pc
    service: switch.turn_on
- id: '1540143489531'
  alias: Show message on Bedroom TV
  trigger:
  - entity_id: input_text.bedroom_tv_message
    platform: state
  condition: []
  action:
  - service: rest_command.bedroom_tv_message
- id: '1540533333691'
  alias: Slack Notify New Device
  trigger:
  - event_data: {}
    event_type: device_tracker_new_device
    platform: event
  condition: []
  action:
  - data:
      message: New device!
    service: notify.slack
- id: '1543758079076'
  alias: Slack Intercom Notify
  trigger:
  - platform: webhook
    webhook_id: intercom
  condition: []
  action:
  - data:
      entity_id: camera.intercom_camera
      filename: /tmp/intercom.jpg
    service: camera.snapshot
  - data:
      data:
        file:
          path: /tmp/intercom.jpg
      message: Knock-knock!
      title: intercom
    service: notify.slack
