homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.230345
  longitude: 50.189222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Samara
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp

# Show links to resources in log and frontend
#introduction:

recorder:
  exclude:
    domains:
      - automation
    entities:
      - camera.porch_camera
      - camera.bedroom_tv_image
      - sensor.bedroom_tv_challenge
      - input_text.bedroom_tv_message
      - sensor.kicker_team

# Enables the frontend
frontend:
  themes:
    midnight: !include theme_midnight.yaml

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
  - samsung_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
#tts:
#  - platform: google

# Cloud

cloud:
input_text:
  bedroom_tv_message:
    name: Message

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
  love:
    title: Love
    icon: mdi:heart
    url: /lovelace

device_tracker:
- platform: ddwrt
  host: 192.168.1.1
  username: UksusoFF
  password: !secret router_password
  track_new_devices: true
  interval_seconds: 120
  new_device_defaults:
    track_new_devices: false

rest_command:
  bedroom_tv_shutdown:
    url: !secret bedroom_tv_shutdown_url
  bedroom_tv_message:
    url: ""

switch:
- platform: wake_on_lan
  host: "192.168.1.5"
  name: "Kirill's PC"
  mac_address: !secret kirills_pc_mac

weather:
- platform: openweathermap
  name: Weather
  api_key: !secret openweathermap_key
  
binary_sensor:
  - platform: ping
    host: 192.168.1.50
    name: bedroom_tv_ping
    friendly_name: Bedroom TV

sensor:
  - platform: command_line
    name: Kicker Team
    command: "shuf -e Kirill Denis Andrey Anton"
    scan_interval: 86400
  - platform: template
    sensors:
      bedroom_tv_challenge:
        value_template: !secret bedroom_tv_challenge
      test_tv_message:
        value_template: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?action=ALERT&type=CENTER&challenge={{ states('sensor.bedroom_tv_challenge') }}&message={{ states('input_text.bedroom_tv_message') }}"
#- platform: rest
#  resource: !secret bedroom_tv_info_url
#  name: bedroom_tv
#  friendly_name: Bedroom TV
#  json_attributes:
#  - source
#  - tv_mode
#  - volume
#  - channel_number
#  - channel_name
#  - program_name
#  scan_interval: '00:05'
#- platform: template
#  sensors:
#    bedroom_tv_source:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.source }}'
#      friendly_name: Source
#    bedroom_tv_mode:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.tv_mode }}'
#      friendly_name: Mode
#    bedroom_tv_volume:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.volume }}'
#      friendly_name: Volume
#    bedroom_tv_channel_number:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.channel_number }}'
#      friendly_name: Channel Number
#    bedroom_tv_channel_name:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.channel_name }}'
#      friendly_name: Channel Name
#    bedroom_tv_program_name:
#      value_template: '{{ states.sensor.bedroom_tv.attributes.program_name }}'
#      friendly_name: Program Name

camera:
- platform: generic
  name: Bedroom TV Image
  still_image_url: !secret bedroom_tv_image_url
- platform: ffmpeg
  name: Porch Camera
  input: "rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?"

notify:
- name: Slack
  platform: slack
  api_key: !secret slack_token
  default_channel: '#home'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
