homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.230345
  longitude: 50.189222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Samara
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /tmp

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:

hacs:
  token: !secret github_token

# Discover some devices automatically
discovery:
  ignore:
  - samsung_tv

mqtt:
  discovery: true
  discovery_prefix: homeassistant
  
# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Cloud
cloud:

map:

recorder:
  exclude:
    domains:
      - automation
      - camera
      - route
      - hacs
    entities:
      - sensor.bedroom_tv_challenge
      - sensor.bedroom_tv_info_url
      - sensor.kicker_team
      - input_text.bedroom_tv_message

lovelace:
  mode: yaml

input_text:
  bedroom_tv_message:
    name: Message

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: UksusoFF
    password: !secret router_password
    track_new_devices: true
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: true

rest_command:
  bedroom_tv_shutdown:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=SHUTDOWN"
  bedroom_tv_play:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_PLAY"
  bedroom_tv_pause:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_PAUSE"
  bedroom_tv_vol_up:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_VOLUP"
  bedroom_tv_vol_down:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_VOLDOWN"
  bedroom_tv_message:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=ALERT&type=CENTER&message={{ states('input_text.bedroom_tv_message') }}"

switch:
  - platform: wake_on_lan
    host: 192.168.1.5
    name: "Kirill's PC"
    mac_address: !secret kirills_pc_mac
  - platform: wake_on_lan
    host: 192.168.1.52
    name: "living_room_tv_on"
    mac_address: !secret hisens_tv_mac
#  - platform: mqtt
#    name: "living_room_tv_off"
#    state_topic: "/remoteapp/mobile/broadcast/ui_service/state"
#    command_topic: "/remoteapp/tv/remote_service/HomeAssistant/actions/sendkey"
#    payload_on: "KEY_POWER"
#    optimistic: false
#    qos: 0
#    retain: false
#  - platform: template
#    switches:
#      living_room_tv:
#        value_template: "{{ is_state('binary_sensor.living_room_tv', 'on') }}"
#        turn_on:
#          service: switch.turn_on
#          data:
#            entity_id:  switch.living_room_tv_on
#        turn_off:
#          service: switch.turn_on
#          data:
#            entity_id:  switch.living_room_tv_off
  - platform: rpi_gpio
    ports:
      6: Bedroom Light
      13: Children Room Light
      19: Hallway Light
      26: Living Room Light

weather:
  - platform: openweathermap
    name: Weather
    api_key: !secret openweathermap_key

binary_sensor:
  - platform: ping
    host: 192.168.1.50
    name: Bedroom TV
#  - platform: ping
#    host: 192.168.1.52
#    name: Living Room TV
#    count: 2
#    scan_interval: 2
  - platform: ping
    host: 8.8.8.8
    name: Internet
    count: 1
    scan_interval: 30

sensor:
  - platform: template
    sensors:
      bedroom_tv_challenge:
        value_template: !secret bedroom_tv_challenge
      bedroom_tv_info_url:
        value_template: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=CHANNELINFO"
  - platform: rpi_power
    text_state: true

camera:
  - platform: generic
    name: Bedroom TV Image
    still_image_url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=SNAPSHOT"
  - platform: ffmpeg
    name: Porch Camera
    input: "rtsp://192.168.1.10:554/user=admin&password=&channel=1&stream=0.sdp?"
  - platform: ffmpeg
    name: Intercom Camera
    input: "rtsp://192.168.1.10:554/user=admin&password=&channel=2&stream=0.sdp?"
  - platform: ffmpeg
    name: First Floor Camera
    input: "rtsp://192.168.1.10:554/user=admin&password=&channel=3&stream=0.sdp?"

notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_token
    default_channel: '#home'
  - name: Facebook
    platform: facebook
    page_access_token: !secret facebook_token

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
