homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.230345
  longitude: 50.189222
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Samara
  # Customization file
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp
    - /config/tmp

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

#breaking_changes:

system_health:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
updater:

mobile_app:

hacs:
  token: !secret github_token

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Cloud
cloud:

map:

#recorder:
#  purge_keep_days: 7
#  exclude:
#    domains:
#      - automation
#      - camera
#      - route
#      - hacs
#    entities:
#      - sensor.bedroom_tv_challenge
#      - sensor.bedroom_tv_info_url
#      - input_text.bedroom_tv_message

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /local/custom/tosamara-card/tosamara-card.js
      type: module

input_text:
  bedroom_tv_message:
    name: Message

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: UksusoFF
    password: !secret router_password
    track_new_devices: true
    interval_seconds: 120
    new_device_defaults:
      track_new_devices: true
  - platform: nmap_tracker
    hosts:
      - 192.168.1.53

rest_command:
  bedroom_tv_shutdown:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=SHUTDOWN"
  bedroom_tv_play:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_PLAY"
  bedroom_tv_pause:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_PAUSE"
  bedroom_tv_vol_up:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_VOLUP"
  bedroom_tv_vol_down:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=KEY&key=KEY_VOLDOWN"
  bedroom_tv_message:
    url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=ALERT&type=CENTER&message={{ states('input_text.bedroom_tv_message') }}"
  google_backup:
    url: "http://localhost:8055/gb/doBackup"
    timeout: 300
  domru_open_door_630900288544:
    url: http://192.168.1.51:10080/api/open/630900288544/3221590/41833

script:
  domru_open_door_630900288544:
    sequence:
      - service: rest_command.domru_open_door_630900288544

shell_command:
  dvr_slack: bash /config/_scripts/dvr-slack.sh

switch:
  - platform: wake_on_lan
    host: 192.168.1.5
    name: "Kirill's PC"
    mac: !secret kirills_pc_mac
  - platform: wake_on_lan
    host: 192.168.1.53
    name: Hisense TV
    mac: !secret hisense_tv_mac_wifi
  - platform: rpi_gpio
    invert_logic: false
    ports:
      14: Hallway Light
      15: Children Room Light
      18: Bedroom Light
      23: Bathroom Light
      3: Living Room Light
      4: Kitchen Main Light
      27: Kitchen Second Light
      22: Free One

binary_sensor:
  - platform: ping
    host: 192.168.1.50
    name: Bedroom TV
#  - platform: ping
#    host: 192.168.1.54
#    name: Living Room TV Box
#    count: 2
#    scan_interval: 2
  - platform: ping
    host: 8.8.8.8
    name: Internet
    count: 1
    scan_interval: 30

sensor:
  - platform: template
    sensors:
      bedroom_tv_challenge:
        value_template: !secret bedroom_tv_challenge
      bedroom_tv_info_url:
        value_template: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=CHANNELINFO"
#  - platform: rpi_power
#    text_state: true
#  - platform: mqtt
#    name: Hisense TV Source
#    state_topic: "/remoteapp/mobile/broadcast/ui_service/state"
#    value_template: "{{ value_json.sourcename }}"
#    expire_after: 30
#    force_update: true
  - platform: mqtt
    name: Google Backup
    state_topic: "googlebackup/result"
    json_attributes_topic: "googlebackup/result"

sonoff:
  username: !secret sonoff_email
  password: !secret sonoff_password
  mode: local
  reload: always

home_connect:
  client_id: !secret home_connect_id
  client_secret: !secret home_connect_secret

camera:
  - platform: generic
    name: Bedroom TV Image
    still_image_url: "http://192.168.1.50:1080/cgi-bin/samygo-web-api.cgi?challenge={{ states('sensor.bedroom_tv_challenge') }}&action=SNAPSHOT"
  - platform: ffmpeg
    name: Porch Camera
    input: "rtsp://192.168.1.21:554/user=admin&password=&channel=1&stream=0.sdp?"
  - platform: ffmpeg
    name: First Floor Camera
    input: "rtsp://192.168.1.21:554/user=admin&password=&channel=2&stream=0.sdp?"
  - platform: ffmpeg
    name: Intercom Camera
    input: "rtsp://192.168.1.21:554/user=admin&password=&channel=3&stream=0.sdp?"
  - platform: ffmpeg
    name: Key Room Camera
    input: "rtsp://192.168.1.21:554/user=admin&password=&channel=4&stream=0.sdp?"
  - platform: ffmpeg
    name: New Camera One
    input: "rtsp://192.168.1.30:554/user=admin&password=&channel=1&stream=0.sdp?"
  - platform: ffmpeg
    name: New Camera Two
    input: "rtsp://192.168.1.31:554/user=admin&password=&channel=1&stream=0.sdp?"
  - platform: generic
    name: domru_domofon_17666535
    still_image_url: http://192.168.1.51:10080/api/camera/snapshot/630900288544/17666535
    stream_source: http://192.168.1.51:10080/api/camera/stream/630900288544/17666535

notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_token
    default_channel: '#home'
  - name: Facebook
    platform: facebook
    page_access_token: !secret facebook_token

group: !include groups.yaml
automation: !include automations.yaml
