title: My Awesome Home

views:

  - title: Home
    icon: mdi:home-assistant
    id: home
    cards:
      - type: glance
        entities:
        - device_tracker.oukitel_wp5_pro
        - device_tracker.redmi_note_8t
      - type: entities
        entities:
        - binary_sensor.internet
        - sun.sun
      - type: weather-forecast
        entity: weather.home

  - title: Bedroom
    icon: mdi:bed
    cards:
      - type: vertical-stack
        cards:
          - type: custom:button-card
            entity: switch.bedroom_light
            show_name: false
            icon: mdi:lightbulb
            state:
            - value: "on"
              color: "#44739e"
            - operator: default
              color: "#FDD835"
          - type: custom:vertical-stack-in-card
            title: TV
            cards:
            - type: entities
              show_header_toggle: false
              entities:
              - entity: binary_sensor.bedroom_tv
                name: Status
                icon: mdi:television-classic
              - entity: input_text.bedroom_tv_message
            - type: horizontal-stack
              cards:
                - type: custom:button-card
                  icon: mdi:power-plug-off
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_shutdown
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:pause
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_pause
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:play
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_play
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:volume-minus
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_vol_down
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:volume-plus
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_vol_up
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
            - type: picture-entity
              entity: camera.bedroom_tv_image
              
  - title: Porch
    icon: mdi:outdoor-lamp
    cards:
    - type: picture-entity
      entity: camera.porch_camera
    - type: picture-entity
      entity: camera.intercom_camera
    - type: picture-entity
      entity: camera.first_floor_camera
    - type: picture-entity
      entity: camera.key_room_camera
    - type: picture-entity
      entity: camera.new_camera_one
    - type: picture-entity
      entity: camera.new_camera_two
    - type: picture-glance
      title: Intercom
      entities:
        - entity: script.domru_open_door_630900288544
          icon: "mdi:door-open"
          name: Open
          tap_action:
            action: toggle
      hold_action:
          action: call-service
          service: rest_command.domru_open_door_630900288544
      camera_image: camera.domru_domofon_17666535

  - title: Kitchen
    icon: mdi:silverware-fork-knife
    cards:
    - type: custom:button-card
      entity: switch.kitchen_main_light
      show_name: false
      icon: mdi:lightbulb-group
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"
    - type: custom:button-card
      entity: switch.kitchen_second_light
      show_name: false
      icon: mdi:led-strip-variant
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"
    - type: glance
      title: Dishwasher
      show_name: false
      entities:
      - sensor.posudomoechnaia_mashina_program_progress
      - binary_sensor.posudomoechnaia_mashina_door
      - switch.posudomoechnaia_mashina_power

  - title: Living Room
    icon: mdi:sofa
    cards:
    - type: custom:button-card
      entity: switch.living_room_light
      show_name: false
      icon: mdi:lightbulb
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"
    - type: entities
      show_header_toggle: false
      entities:
      - automation.turn_on_pc_at_morning
      - entity: switch.kirill_s_pc
        icon: mdi:desktop-tower-monitor
    - type: custom:vertical-stack-in-card
      title: TV
      cards: !include "ui-lovelace-hisense.yaml"

  - title: Children Room
    icon: mdi:gamepad-variant
    cards:
    - type: custom:button-card
      entity: switch.children_room_light
      show_name: false
      icon: mdi:lightbulb
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"

  - title: Hallway
    icon: mdi:door-open
    cards:
    - type: custom:button-card
      entity: switch.hallway_light
      show_name: false
      icon: mdi:lightbulb
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"

  - title: Bathroom
    icon: mdi:shower
    cards:
    - type: custom:button-card
      entity: switch.bathroom_light
      show_name: false
      icon: mdi:lightbulb
      state:
        - value: "on"
          color: "#44739e"
        - operator: default
          color: "#FDD835"
    - type: custom:stack-in-card
      mode: vertical
      cards:
        - type: custom:button-card
          entity: switch.sonoff_1000de2973
          show_name: false
          icon: mdi:radiator
        - type: vertical-stack
          cards:
            - type: entities
              entities:
                - automation.bathroom_heat_on
                - automation.bathroom_heat_off

  - title: Bus Station
    icon: mdi:bus-stop
    cards:
    - type: custom:tosamara-card
      title: Телецентр (в город)
      station: 996
    - type: custom:tosamara-card
      title: Динамо (из города)
      station: 376
    - type: custom:tosamara-card
      title: Красноармейская (из города)
      station: 944

