resources:
  - url: /customcards/tracker-card.js?track=true
    type: module
  - url: /customcards/vertical-stack-in-card.js?track=true
    type: module
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module

title: My Awesome Home

views:

  - title: Home
    icon: mdi:home-assistant
    id: home
    cards:
      - type: glance
        entities:
        - device_tracker.android2e62f0295f67a50e
        - device_tracker.android5268f63eb95950f4
      - type: entities
        entities:
        - sun.sun
      - type: weather-forecast
        entity: weather.weather

  - title: Bedroom
    icon: mdi:hotel
    cards:
      - type: vertical-stack
        cards:
          - type: entity-button
            entity: switch.bedroom_light
            show_name: false
            icon: mdi:lightbulb
          - type: custom:vertical-stack-in-card
            title: TV
            cards:
            - type: entities
              show_header_toggle: false
              entities:
              - entity: binary_sensor.bedroom_tv
                name: Status
              - entity: input_text.bedroom_tv_message
            - type: horizontal-stack
              cards:
                - type: custom:button-card
                  icon: mdi:power-plug-off
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_shutdown
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:pause
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_pause
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:play
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_play
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:volume-minus
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_vol_down
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
                - type: custom:button-card
                  icon: mdi:volume-plus
                  tap_action:
                    action: call-service
                    service: rest_command.bedroom_tv_vol_up
                    service_data:
                  styles:
                    card:
                      - box-shadow: none
            - type: picture-entity
              entity: camera.bedroom_tv_image
              
  - title: Porch
    icon: mdi:door-open
    cards:
    - type: picture-entity
      entity: camera.porch_camera
    - type: picture-entity
      entity: camera.intercom_camera
    - type: picture-entity
      entity: camera.first_floor_camera

  - title: Kitchen
    icon: mdi:silverware-fork-knife
    cards:      

  - title: Living Room
    icon: mdi:sofa
    cards:
    - type: entity-button
      entity: switch.living_room_light
      show_name: false
      icon: mdi:lightbulb
    - type: entities
      entities:
      - automation.turn_on_pc_at_morning
      - switch.kirill_s_pc

  - title: Children Room
    icon: mdi:gamepad-variant
    cards:
    - type: entity-button
      entity: switch.children_room_light
      show_name: false
      icon: mdi:lightbulb

  - title: Hallway
    icon: mdi:door-open
    cards:
    - type: entity-button
      entity: switch.hallway_light
      show_name: false
      icon: mdi:lightbulb

  - title: Config
    cards:
    - type: custom:tracker-card